### ISSUE TITLE
Space cargo wagon robot port not working as intended

### ISSUE THREAD

**Issue by Bykow** [Fragjacker/se-space-trains#10]
Hello !

I noticed that the space cargo wagon does not emulate the same behavior than its terrestrial counterpart. 

The terrestrial one, when equipped with robots ports will behave properly to the condition "Robot inactivity". But the space cargo wagon won't. It will only work if the train is set to manual. 

Fixing this could allow to use the train scheduling feature properly.

**Comment by Fragjacker** [comment]
I'll take a look at this, maybe I forgot to paste some code from the base trains somewhere.

**Comment by Dominowood371** [comment]
This can be fixed by adding a property:  `allow_robot_dispatch_in_automatic_mode = true,`
