### ISSUE TITLE
Factorio 2.0

### ISSUE THREAD

**Issue by BraveCaperCat2** [Fragjacker/se-space-trains#12]
Now that Factorio: Space Age has released, and with it the 2.0 update. Please make your mod compatible with the new version.

**Comment by Fragjacker** [comment]
I am on it. Thankfully @tburrows13 has helped me tremendously with his pull request, bringing the code aspect of the mod up to speed. All that is left to do now, is to re-render the sprites to account for the vertical rotation when trains enter/leave elevated rail ramps.
