### ISSUE TITLE
Destroyed PowerPacks

### ISSUE THREAD

**Issue by ourpxi** [Fragjacker/se-space-trains#13]
Hey there,
I wasn't able to open a discussion on the Factorio mod page so I do it here
I couldn't found a way to recicle or do something with the destroyed power packs, it would be great if they could be put onto the recycling machine or used to make new power packs by reducing the amount of the other resources required to make them

**Comment by Fragjacker** [comment]
@ourpxi This should be fixed as of the latest mod update. I simply forgot to add the refurbishment recipe to Space Age 😄.
