### ISSUE TITLE
The weight of the locomotive might be too high?

### ISSUE THREAD

**Issue by snouz** [Fragjacker/se-space-trains#14]
Hi, I tested your mod and compared the speed of the normal locomotive and yours, and noticed the acceleration wasn't that different. The reason being that despite using way more power, the weight is 12k, compared to normal one's 2k. So if my math is correct, it needs 6x the power to accelerate equally, but it's only 6.6x more powerful. (600kW vs 4000kW). For comparison, electric trains are way faster, simply because they're lighter. Tell me what you think.

**Comment by snouz** [comment]
For info, this version has 4T locomotives. Real electric cars are only 10/15% heavier than thermal ones according to google.

**Comment by Fragjacker** [comment]
I think the reason I made it this high back in the day was, that the trains would be zooming _really_ fast. 4000 sounds reasonable though.
